// Used to display the data offline first;

export default {
	"login": "evansibok",
	"id": 16621400,
	"node_id": "MDQ6VXNlcjE2NjIxNDAw",
	"avatar_url": "https://avatars0.githubusercontent.com/u/16621400?v=4",
	"gravatar_id": "",
	"url": "https://api.github.com/users/evansibok",
	"html_url": "https://github.com/evansibok",
	"followers_url": "https://api.github.com/users/evansibok/followers",
	"following_url": "https://api.github.com/users/evansibok/following{/other_user}",
	"gists_url": "https://api.github.com/users/evansibok/gists{/gist_id}",
	"starred_url": "https://api.github.com/users/evansibok/starred{/owner}{/repo}",
	"subscriptions_url": "https://api.github.com/users/evansibok/subscriptions",
	"organizations_url": "https://api.github.com/users/evansibok/orgs",
	"repos_url": "https://api.github.com/users/evansibok/repos",
	"events_url": "https://api.github.com/users/evansibok/events{/privacy}",
	"received_events_url": "https://api.github.com/users/evansibok/received_events",
	"type": "User",
	"site_admin": false,
	"name": "Evans Ibok",
	"company": null,
	"blog": "evansibok.com",
	"location": "Nigeria",
	"email": null,
	"hireable": true,
	"bio": "Frontend Developer, UXer, Coffee Lover. ENFP",
	"public_repos": 48,
	"public_gists": 0,
	"followers": 17,
	"following": 18,
	"created_at": "2016-01-09T09:10:21Z",
	"updated_at": "2019-12-03T11:29:42Z"
}